dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install black flake8
  - pip install .
script:
  - black --check sdarray
  - flake8 sdarray
  - pytest tests
jobs:
  include:
    - stage: coverage
      python: "3.7"
      install:
        - pip install pytest-cov codecov
        - pip install .
      script:
        - pytest tests --cov sdarray
      after_success:
        - codecov
    - stage: deploy
      python: "3.7"
      install:
        - pip install sphinx sphinx-rtd-theme
        - pip install .
      script:
        - sphinx-apidoc -f -o docs/_apidoc sdarray
        - sphinx-build docs docs/_build
        - sphinx-build docs docs/_build
      deploy:
        provider: pages
        local-dir: docs/_build
        target-branch: gh-pages
        github-token: $GITHUB_TOKEN
        skip-cleanup: true
        keep-history: true
        on:
          branch: master
