#!/bin/bash
set -eu

VERSION=${1}
VERSION_ERE='[0-9]+\.[0-9]+\.[0-9]+'

# check version format
if ! echo ${VERSION} | grep -E ^${VERSION_ERE}$ >/dev/null 2>&1
then
    echo 'Error: version must be <major>.<minor>.<patch>'
    exit 1
fi

# update version written in files
for f in setup.cfg sdarray/*.py docs/*.py tests/*.py
do
    find ${f} -type f | xargs sed -i '' -E s/${VERSION_ERE}/${VERSION}/g
done

# publish source distribution
python setup.py sdist
twine upload dist/$(python setup.py --fullname).tar.gz
